# Control file for continuous integration testing at http://travis-ci.org/

language: c

script:
- make CC=clang NESTED_QSORT=0 && ./example_sort && make clean
- make CC=gcc NESTED_QSORT=0 && ./example_sort && make clean
- make CC=gcc NESTED_QSORT=1 && ./example_sort && make clean
